framework:
            csrf_protection: true
            templating:
                engines: ['twig']

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User  # <--- Note the namespace must be App not AppBundle
    from_email:
        address: "%env(MAILER_ADDRESS)%"
        sender_name: "%env(MAILER_SENDER_NAME)%"