knp_menu:
  # use "twig: false" to disable the Twig extension and the TwigRenderer
  twig:
#    template: KnpMenuBundle::menu.html.twig
#    template: admin/partials/left_column_menu.html.twig
  #  if true, enables the helper for PHP templates
  templating: true
  # the renderer to use, list is also available by default
  default_renderer: twig